#HOME FOLDER OF SOFTWARES : to replace by the paths on your machine
ORTHOFINDER_PROGRAM: "orthofinder"
MACSE_PROGRAM: "/usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/macse_v2.06.jar"   # "/mnt/users/thut/bin/macse_v2.03.jar"
TREEBEST_PROGRAM: "treebest"
I-ADHORE_PROGRAM: "i-adhore"
MAFFT_PROGRAM: "mafft"

#OUTPUT RESULT FOLDER
OUTPUT_FOLDER: "results"                                        #the main folder contains all results
TEMP_FOLDER: "/usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/"                                      #the temporary folder when running orthofider
PREP_FOLDER: "PrepInput_pipeline"                               #the sub-folder, located inside the main folder, which contains all data downloaded, converted into convenient format for running the ortho_pipeline
ORTHO_FOLDER: "Ortho_pipeline"                                  #the sub-folder, located inside the main folder, contains the results of the ortho_pipeline
ALIGN_FOLDER: "Alignments"                                      #the sub-folder, located inside the ORTHO_FOLDER, contains the cds alignments
TREEBEST_FOLDER: "Treebest"                                     #the sub-folder, located inside the ORTHO_FOLDER, contains the gene trees, and ds distance generated by treebest using the cds alignments
SYNTENY_FOLDER: "Synteny_pipeline"                              #the sub-folder, located inside the main folder, contains the input and results of i-adhore.
SYNTENY_WHOLE_OG_FOLDER: "whole_OG"                             #the sub-folder, located inside the SYNTENY_FOLDER/Input or Result folder, contains the input/results of the synteny on whole OG
SYNTENY_CLANS_FOLDER: "clans"                                   #the sub-folder, located inside the SYNTENY_FOLDER/Input or Result folder, contains the input/results of the synteny on clans (including species preWGD + postWGD)

#NUMBER OF THREADS
NBTHREADS_ORTHOFINDER: 60                                       #number of threads for running orthofinder
NBTHREADS_IADHORE: 20                                            #number of threads for running i-adhore
IADHORE_MPI: True                                               #Use parallel mode for i-adhore, need compatible mpi library. Should be either True or False

OGVERSION: 1v                                                     #the version which will be appended into the ortholog names

#PARAMETER FOR CDS-ALIGNMENTS
##As MACSE is very time-consuming for big orthogroups and long sequences, we switch to an alternative methode (using mafft on AA and then convert back to CDS) when the orthogroups are big. These 2 parameters decide the limit when the cds alignment is processed with MACSE.
MAX_NBSEQ_MACSE: 200                                            #Maximum number of genes that the cds alignment will be done with MACSE
MAX_LENSEQ_MACSE: 10000                                         #Maximum gene length that the cds alignment will be done with MACSE

##SOME OPTIONS TO RUN PIPELINE
LEVEL2_ONLY: True                                               #If True, then only generate ohnolog table for level-2 of i-adhore results. If False, then generate ohnolog table for all levels.
SPLIT_OG_BEFORE_CDS_ALIGNMENT: False                            #If True, then use the duplication events in the Resolved Gene Trees of Orthofinder to split the orthogroups before processing cds alignments. If False, then process the cds alignments on the whole orthogoups.
CDS_ALIGNMENT_CLANS_ONLY: False                                 #Only use the genes of the species in clans for cds alignments and build cds trees (clan species are postWGD+preWGD). If False, then use genes of all species to build cds alignments and cds trees.
EXTRACT_CLANS: True                                             #Extract clans trees and cds_alignments from cds trees. If False, then do not extract clan trees.
FINDDUP: True                                                   #Find clans that have WGD nodes
MIN_CLANS_SIZE: 3                                               #Minimum number of genes in an extracted clan
SUPPORT_CLANS_TREES: 0.7                                        #Only extract clans with support value >= this threshold
SUPPORT_DUP_TREES: 0.7                                          #Minimum support for WGD node 

###Meta data
#preWGD:
#- Eluc
#postWGD:
#- Tthy
#- Hhuc
#- Salp
#- Okis
#- Omyk
#- Ssal
#- Stru
#inputFiles:
#  Tthy:
#    common_name: Grayling
#    scientific_name: Thymallus_thymallus
#    source: local
#    protein_fasta: /local/genome/references/Thymallus_thymallus/2018-CEES/Tthy2_maker_filter2_proteins.fasta
#    cds_fasta: /mnt/users/garethg/species_data/Tthy/Tthy.cds.fa
#    gff: /local/genome/references/Thymallus_thymallus/2018-CEES/Maker_filtered_m_filter2.gff


inputFiles:
	Aara:
                common_name: Aara
		scientific_name : A.ara
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/A.ara.pep.fa
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/A.ara.cds.fa
		gff : 
	Alyr:
		common_name: Alyr
		scientific_name : Alyr
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/Aly.pep.fa
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/Aly.cds.fa
		gff : 
	Atha:
		common_name: Atha
		scientific_name : Atha
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/A.tha.pep.fa
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/A.tha.cds.fa
		gff : 
	Bnig:
		common_name: Bnig
		scientific_name : Bnig
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/Bnigra_NI100.v2.pep.fasta
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/Bnigra_NI100.v2.cds.fasta
		gff : 
	Bole:
		common_name: Bole
		scientific_name : Bole
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/BoleraceaHDEM_proteins.fasta
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/BoleraceaHDEM_CDS.fasta
		gff : 
	Brap:
		common_name: Brap
		scientific_name : Brap
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/Brapa_genome_v3.0_pep.fasta
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/Brapa_genome_v3.0_cds.fasta
		gff : 
		
	Crub:
		common_name: Crub
		scientific_name : Crub
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/C.rub.pep.fa
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/C.rub.cds.fa
		gff :

	Esal:
		common_name: Esal
		scientific_name : Esal
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/E.sal.pep.fa
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/E.sal.cds.fa
		gff :
	Il:
		common_name: Il
		scientific_name : Il
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/Il.best.pep.fa
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/Il.cds.fasta
		gff :
	Lala:
		common_name: Lala
		scientific_name : Lala
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/Lala.pep
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/Lala.cds
		gff :
	Mpyg:
		common_name: Mpyg
		scientific_name : Mpyg
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/Mpyg.pep.fa
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/Mpyg.cds.fa
		gff :
	Ovio:
		common_name: Ovio
		scientific_name : Ovio
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/Ovio_best.pep.fa
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/Ovio_best.cds.fa
		gff :
	Siri:
		common_name: Siri
		scientific_name : Siri
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/Siri.pep
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/Siri.cds
		gff :
	Tarv:
		common_name: Tarv
		scientific_name : Tarv
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/T.arv.pep.fa
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/T.arv.cds.fa
		gff :
	Tpar:
		common_name: Tpar
		scientific_name : Tpar
		source :local
		protein_fasta : /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/pep/T.par.pep.fa
		cds_fasta: /usr_storage/jcf/2.zhugecai/00.diploid/14.gene_family/3.gene_family/2.ortho/orthofinder/cds/T.par.cds.fa
		gff :


